name: Unity
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight
  push:
    branches: ['main']
  pull_request:
    branches: ['*']
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: .github/
      - uses: RageAgainstThePixel/job-builder@v1
        id: setup-jobs
        with:
          build-options: ./.github/workflows/build-options.json
          group-by: unity-version
    outputs:
      jobs: ${{ steps.setup-jobs.outputs.jobs }}
  validate:
    if: ${{ needs.setup.outputs.jobs }}
    needs: setup
    name: build ${{ matrix.jobs.name }}
    permissions:
      contents: read
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.jobs) }}
      fail-fast: false
    secrets: inherit
    uses: RageAgainstThePixel/workflows/.github/workflows/build-unity-test-project.yml@main
    with:
      matrix: ${{ toJSON(matrix.jobs.matrix) }}
